//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ER4Aerea
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cidade:Dominio
    {
        public int id { get; set; }
        public string nome { get; set; }
        public string cep { get; set; }

        public Cidade(string nome, string cep) {
            this.nome = nome;
            this.cep = cep;
        }
    }
}
