//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ER4Aerea.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CIDADE
    {
        public CIDADE()
        {
            this.VOOs = new HashSet<VOO>();
            this.VOOs1 = new HashSet<VOO>();
            this.CLIENTEs = new HashSet<CLIENTE>();
            this.USUARIOs = new HashSet<USUARIO>();
        }
    
        public decimal ID_CIDADE { get; set; }
        public string NOM_CIDADE { get; set; }
        public decimal NUM_CEP { get; set; }
    
        public virtual ICollection<VOO> VOOs { get; set; }
        public virtual ICollection<VOO> VOOs1 { get; set; }
        public virtual ICollection<CLIENTE> CLIENTEs { get; set; }
        public virtual ICollection<USUARIO> USUARIOs { get; set; }
    }
}
