//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ER4Aerea.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENTE
    {
        public CLIENTE()
        {
            this.RESERVAs = new HashSet<RESERVA>();
        }
    
        public decimal ID_CLIENTE { get; set; }
        public string FLG_PROMOCAO { get; set; }
        public string NOM_CLIENTE { get; set; }
        public string NOM_EMAIL { get; set; }
        public string NOM_ENDERECO { get; set; }
        public decimal NUM_CPF { get; set; }
        public decimal ID_CIDADE { get; set; }
        public string NUM_CELULAR { get; set; }
        public decimal VAL_RENDA { get; set; }
        public string NOM_OCUPACAO { get; set; }
        public string FLG_ESPECIAL { get; set; }
        public string NUM_RG { get; set; }
        public string SEXO { get; set; }
        public decimal NUM_END { get; set; }
        public string NOM_BAIRRO { get; set; }
        public string CAD_CEP { get; set; }
        public string NUM_TELEFONE { get; set; }
        public decimal PER_DESCONTO { get; set; }
    
        public virtual CIDADE CIDADE { get; set; }
        public virtual ICollection<RESERVA> RESERVAs { get; set; }
    }
}
