//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ER4Aerea.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AVIAO> AVIAOs { get; set; }
        public DbSet<CIDADE> CIDADEs { get; set; }
        public DbSet<CLIENTE> CLIENTEs { get; set; }
        public DbSet<RESERVA> RESERVAs { get; set; }
        public DbSet<USUARIO> USUARIOs { get; set; }
        public DbSet<VOO> VOOs { get; set; }
    }
}
