//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ER4Aerea.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities2 : DbContext
    {
        public Entities2()
            : base("name=Entities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AVIAO> AVIAO { get; set; }
        public DbSet<CIDADE> CIDADE { get; set; }
        public DbSet<CLIENTE> CLIENTE { get; set; }
        public DbSet<RESERVA> RESERVA { get; set; }
        public DbSet<USUARIO> USUARIO { get; set; }
        public DbSet<VOO> VOO { get; set; }
    }
}
